name: CI

on:
  push:
    branches: 
      - master
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - '**'


jobs:
  check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/chain

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      # Restore the yarn cache
      - uses: c-hive/gha-yarn-cache@v1
      
      - name: Yarn install
        run: yarn install

      - name: Build
        run: yarn hardhat compile

      - name: Test
        run: yarn hardhat test

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            artifacts/contracts/Curve.sol/Curve.json
            artifacts/contracts/Eth_broker.sol/Eth_broker.json
            artifacts/contracts/Token.sol/Token.json
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}